
package com.mb.android.nzbAirPremium.db;

import com.j256.ormlite.field.DatabaseField;

public class DbEntry {

	// id is generated by the database and set on the object automagically
	private @DatabaseField(generatedId = true)
	int id;

	public int getId() {
		return id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getBucket() {
		return bucket;
	}

	public void setBucket(String bucket) {
		this.bucket = bucket;
	}

	public String getKey() {
		return key;
	}

	public void setKey(String key) {
		this.key = key;
	}

	public String getValue() {
		return value;
	}

	public void setValue(String value) {
		this.value = value;
	}

	public String getExtra() {
		return extra;
	}

	public void setExtra(String extra) {
		this.extra = extra;
	}

	public static final String BUCKET_FIELD_NAME = "bucket";
	private @DatabaseField(columnName = BUCKET_FIELD_NAME)
	String bucket;

	public static final String KEY_FIELD_NAME = "key";
	private @DatabaseField(columnName = KEY_FIELD_NAME)
	String key;

	public static final String VALUE_FIELD_NAME = "value";
	private @DatabaseField(columnName = VALUE_FIELD_NAME)
	String value;

	public static final String EXTRA_FIELD_NAME = "extra";
	private @DatabaseField(canBeNull = false, columnName = EXTRA_FIELD_NAME)
	String extra;

}
